title: COVID-19 Social Distance Strategies
url: "covid-19-sds.github.io"
baseurl: "/"

markdown: kramdown

tracking_id: UA-45164598-5

footer: yes
footer_url: ""
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Team"
   link: "team"
 - name: "Contact"
   link: "contact"

github: [metadata]